spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: cloud-config-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
config:
  info: version=dev-2
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: cloud-config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
config:
  info: version=test-1
---
server:
  port: 8203
spring:
  profiles: prod
  application:
    name: cloud-config-client-prod
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
config:
  info: version=prod-1
